# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

# springboot 整合mybatis
mybatis:
  mapper-locations: classpath:com.offcn.mapper/*.xml
  type-aliases-package: com.offcn.pojo